Using the latest cached version of the dataset since flwrlabs/pacs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/apiasecz/.cache/huggingface/datasets/flwrlabs___pacs/default/0.0.0/394113073258ead631f617d2e13bb377c0715c4b (last modified on Wed Jan 29 16:59:35 2025).
Using the latest cached version of the dataset since flwrlabs/pacs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/apiasecz/.cache/huggingface/datasets/flwrlabs___pacs/default/0.0.0/394113073258ead631f617d2e13bb377c0715c4b (last modified on Wed Jan 29 16:59:35 2025).
Using the latest cached version of the dataset since flwrlabs/pacs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at /home/apiasecz/.cache/huggingface/datasets/flwrlabs___pacs/default/0.0.0/394113073258ead631f617d2e13bb377c0715c4b (last modified on Wed Jan 29 16:59:35 2025).
Device: cuda
CUDA Version: 12.1
cuDNN Version: 8902
PyTorch Version: 2.3.0

Model used: PACSCNN
Initial dataset creation
Initial dataset creation
Initial loss: 56.754520416259766
<__main__.Policy object at 0x1510df7d2a50>
56.754520416259766
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 1 took 4.97071099281311s, results:
{'t': 0, 'current_accuracy': 0.2578125, 'current_loss': 52.030019760131836, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 1.9073486328125e-06; Loss Difference: 0.0, Decision: 0
Round 2 took 4.602368593215942s, results:
{'t': 1, 'current_accuracy': 0.2578125, 'current_loss': 52.03002166748047, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 9.5367431640625e-06; Loss Difference: 0.0, Decision: 0
Round 3 took 4.709660530090332s, results:
{'t': 2, 'current_accuracy': 0.2578125, 'current_loss': 52.030029296875, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 1.1444091796875e-05; Loss Difference: 0.0, Decision: 0
Round 4 took 4.888192653656006s, results:
{'t': 3, 'current_accuracy': 0.2578125, 'current_loss': 52.03003120422363, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 3.814697265625e-06; Loss Difference: 0.0, Decision: 0
Round 5 took 4.309786081314087s, results:
{'t': 4, 'current_accuracy': 0.2578125, 'current_loss': 52.0300235748291, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 6 took 3.9352610111236572s, results:
{'t': 5, 'current_accuracy': 0.2578125, 'current_loss': 52.0300178527832, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 5.7220458984375e-06; Loss Difference: 0.0, Decision: 0
Round 7 took 4.866051912307739s, results:
{'t': 6, 'current_accuracy': 0.2578125, 'current_loss': 52.0300235748291, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 9.5367431640625e-06; Loss Difference: 0.0, Decision: 0
Round 8 took 4.123179912567139s, results:
{'t': 7, 'current_accuracy': 0.2578125, 'current_loss': 52.03002738952637, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 7.62939453125e-06; Loss Difference: 0.0, Decision: 0
Round 9 took 4.547018527984619s, results:
{'t': 8, 'current_accuracy': 0.2578125, 'current_loss': 52.030025482177734, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 1.9073486328125e-06; Loss Difference: 0.0, Decision: 0
Round 10 took 4.29333233833313s, results:
{'t': 9, 'current_accuracy': 0.2578125, 'current_loss': 52.030019760131836, 'train_loss': None, 'decision': 0, 'drift_rate': 0, 'target_domains': ['sketch']}
Loss historical diff: 0.0; Loss Difference: 0.0, Decision: 0
Round 11 took 4.3216657638549805s, results:
{'t': 10, 'current_accuracy': 0.2578125, 'current_loss': 52.03001594543457, 'train_loss': None, 'decision': 0, 'drift_rate': 0.001, 'target_domains': ['photo']}
Loss historical diff: 1.1444091796875e-05; Loss Difference: 0.0, Decision: 0
Round 12 took 4.137431859970093s, results:
{'t': 11, 'current_accuracy': 0.2578125, 'current_loss': 52.03002738952637, 'train_loss': None, 'decision': 0, 'drift_rate': 0.001670010459667194, 'target_domains': ['sketch']}
Loss historical diff: 1.1444091796875e-05; Loss Difference: 0.0, Decision: 0
Round 13 took 3.8159706592559814s, results:
{'t': 12, 'current_accuracy': 0.2578125, 'current_loss': 52.03002738952637, 'train_loss': None, 'decision': 0, 'drift_rate': 0.002338845493317048, 'target_domains': ['sketch']}
Loss historical diff: 1.9073486328125e-06; Loss Difference: 0.0, Decision: 0
Round 14 took 3.924600839614868s, results:
{'t': 13, 'current_accuracy': 0.2578125, 'current_loss': 52.0300178527832, 'train_loss': None, 'decision': 0, 'drift_rate': 0.003005331737028868, 'target_domains': ['sketch']}
Loss historical diff: 1.9073486328125e-06; Loss Difference: 0.0, Decision: 1
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 1.00 GiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 514.00 MiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 258.00 MiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 516.00 MiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with an OutOfMemoryError: CUDA out of memory. Tried to allocate 770.00 MiB. GPU  (Triggered internally at /opt/conda/conda-bld/pytorch_1712608847532/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:924.)
  return F.conv2d(input, weight, bias, self.stride,
Traceback (most recent call last):
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 753, in <module>
    main()
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 733, in main
    evaluate_policy_under_drift(
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 554, in evaluate_policy_under_drift
    update_loss = agent_train.update_steps(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/federated/client.py", line 202, in update_steps
    return self.model.update_steps(self.data_loader, optimizer, loss_fn, num_updates, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/models/base_model.py", line 75, in update_steps
    outputs = self.model(inputs)
              ^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 47, in forward
    x = self.features(x)
        ^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
            ^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/execute/evaluate_policy.py", line 70, in forward
    out = self.bn1(out)
          ^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/modules/batchnorm.py", line 175, in forward
    return F.batch_norm(
           ^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cog_fl_llm_env/lib/python3.12/site-packages/torch/nn/functional.py", line 2509, in batch_norm
    return torch.batch_norm(
           ^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 
