Traceback (most recent call last):
  File "/home/apiasecz/programming/concept_drift_optimal_adaptation_FL/src/pretrain_models.py", line 16, in <module>
    from fl_toolkit import *  # Ensure fl_toolkit is correctly installed and accessible
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/__init__.py", line 4, in <module>
    from .data_operations import (
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/data_operations/__init__.py", line 1, in <module>
    from .data_handler import BaseDataHandler
  File "/home/apiasecz/programming/Federated_Learning_Base_Toolkit_torch/fl_toolkit/data_operations/data_handler.py", line 10, in <module>
    from flwr_datasets import FederatedDataset
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/flwr_datasets/__init__.py", line 18, in <module>
    from flwr_datasets import partitioner, preprocessor
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/flwr_datasets/partitioner/__init__.py", line 18, in <module>
    from .dirichlet_partitioner import DirichletPartitioner
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/flwr_datasets/partitioner/dirichlet_partitioner.py", line 23, in <module>
    import datasets
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/datasets/__init__.py", line 17, in <module>
    from .arrow_dataset import Dataset
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/datasets/arrow_dataset.py", line 57, in <module>
    import fsspec
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/fsspec/__init__.py", line 5, in <module>
    from .callbacks import Callback
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/fsspec/callbacks.py", line 324, in <module>
    DEFAULT_CALLBACK = _DEFAULT_CALLBACK = NoOpCallback()
                                           ^^^^^^^^^^^^^^
  File "/home/apiasecz/.conda/envs/cent7/2024.02-py311/cog_fl_llm_env/lib/python3.12/site-packages/fsspec/callbacks.py", line 25, in __init__
    def __init__(self, size=None, value=0, hooks=None, **kwargs):

KeyboardInterrupt
